name: gnome-robots
adopt-info: gnome-robots
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  gnome-robots:
    interface: dbus
    bus: session
    name: org.gnome.Robots

apps:
  gnome-robots:
    extensions: [gnome-3-38]
    command: usr/bin/gnome-robots
    plugs:
      - pulseaudio
    desktop: usr/share/applications/org.gnome.Robots.desktop
    common-id: org.gnome.Robots.desktop

parts:
  gnome-robots:
    source: https://gitlab.gnome.org/GNOME/gnome-robots.git
    source-type: git
    source-tag: '40.0'
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Robots$|=${SNAP}/meta/gui/org.gnome.Robots.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Robots.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Robots.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-robots/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.Robots.appdata.xml]
    organize:
      snap/gnome-robots/current/usr: usr
    build-packages:
      - intltool
      - yelp-tools
